-- MySQL Script generated by MySQL Workbench
-- Thu 31 Jul 2014 22:41:53 CEST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myapp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `myapp` ;

-- -----------------------------------------------------
-- Table `authentication_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authentication_service` ;

CREATE TABLE IF NOT EXISTS `authentication_service` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `system_adapter_service` TEXT NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `identity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `identity` ;

CREATE TABLE IF NOT EXISTS `identity` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `enabled` TINYINT(1) NOT NULL,
  `authentication_enabled` TINYINT(1) NOT NULL,
  `registered_time` DATETIME NULL,
  `display_name` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `identity_authentication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `identity_authentication` ;

CREATE TABLE IF NOT EXISTS `identity_authentication` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_id` INT UNSIGNED NOT NULL,
  `service_id` INT UNSIGNED NOT NULL,
  `identity` TEXT NOT NULL,
  `user_profile` TEXT NULL COMMENT 'json serialized',
  PRIMARY KEY (`id`),
  INDEX `fk_identity_authentication_authentication_service_idx` (`service_id` ASC),
  INDEX `fk_identity_authentication_identity1_idx` (`owner_id` ASC),
  CONSTRAINT `fk_identity_authentication_authentication_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `authentication_service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_identity_authentication_identity1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `identity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Used to store authentication values e.g. facebook userid etc.';


-- -----------------------------------------------------
-- Table `identity_oauth_client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `identity_oauth_client` ;

CREATE TABLE IF NOT EXISTS `identity_oauth_client` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_id` INT UNSIGNED NOT NULL,
  `authentication_service_id` INT UNSIGNED NOT NULL,
  `access_token` TEXT NOT NULL,
  `expires` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_identity_oauth_client_authentication_service1_idx` (`authentication_service_id` ASC),
  INDEX `fk_identity_oauth_client_identity1_idx` (`owner_id` ASC),
  CONSTRAINT `fk_identity_oauth_client_authentication_service1`
    FOREIGN KEY (`authentication_service_id`)
    REFERENCES `authentication_service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_identity_oauth_client_identity1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `identity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `example`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `example` ;

CREATE TABLE IF NOT EXISTS `example` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL DEFAULT NULL,
  `email` TEXT NULL DEFAULT NULL,
  `note` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `oauth_access_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_access_tokens` ;

CREATE TABLE IF NOT EXISTS `oauth_access_tokens` (
  `access_token` VARCHAR(40) NOT NULL,
  `client_id` VARCHAR(80) NOT NULL,
  `user_id` VARCHAR(255) NULL DEFAULT NULL,
  `expires` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `scope` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`access_token`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `oauth_authorization_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_authorization_codes` ;

CREATE TABLE IF NOT EXISTS `oauth_authorization_codes` (
  `authorization_code` VARCHAR(40) NOT NULL,
  `client_id` VARCHAR(80) NOT NULL,
  `user_id` VARCHAR(255) NULL DEFAULT NULL,
  `redirect_uri` VARCHAR(2000) NULL DEFAULT NULL,
  `expires` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `scope` VARCHAR(2000) NULL DEFAULT NULL,
  `id_token` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`authorization_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `oauth_clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_clients` ;

CREATE TABLE IF NOT EXISTS `oauth_clients` (
  `client_id` VARCHAR(80) NOT NULL,
  `client_secret` VARCHAR(80) NOT NULL,
  `redirect_uri` VARCHAR(2000) NOT NULL,
  `grant_types` VARCHAR(80) NULL DEFAULT NULL,
  `scope` VARCHAR(2000) NULL DEFAULT NULL,
  `user_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `oauth_jwt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_jwt` ;

CREATE TABLE IF NOT EXISTS `oauth_jwt` (
  `client_id` VARCHAR(80) NOT NULL,
  `subject` VARCHAR(80) NULL DEFAULT NULL,
  `public_key` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `oauth_refresh_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_refresh_tokens` ;

CREATE TABLE IF NOT EXISTS `oauth_refresh_tokens` (
  `refresh_token` VARCHAR(40) NOT NULL,
  `client_id` VARCHAR(80) NOT NULL,
  `user_id` VARCHAR(255) NULL DEFAULT NULL,
  `expires` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `scope` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`refresh_token`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `oauth_scopes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_scopes` ;

CREATE TABLE IF NOT EXISTS `oauth_scopes` (
  `type` VARCHAR(255) NOT NULL DEFAULT 'supported',
  `scope` VARCHAR(2000) NULL DEFAULT NULL,
  `client_id` VARCHAR(80) NULL DEFAULT NULL,
  `is_default` SMALLINT(6) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `oauth_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_users` ;

CREATE TABLE IF NOT EXISTS `oauth_users` (
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(2000) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `file` ;

CREATE TABLE IF NOT EXISTS `file` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_id` INT UNSIGNED NULL,
  `parent_id` INT UNSIGNED NULL,
  `filesystem` VARCHAR(16) NOT NULL COMMENT 'filesystem handle as they are mount into MountManager',
  `filesystem_path` TEXT NOT NULL,
  `filesystem_error` TEXT NULL COMMENT 'error code as string:' /* comment truncated */ /*NOT_EXISTS*/,
  `type` VARCHAR(8) NOT NULL COMMENT 'file, dir',
  `name` TEXT NOT NULL,
  `mime_type` TEXT NULL,
  `create_time` DATETIME NULL,
  `size` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_file_file1_idx` (`parent_id` ASC),
  INDEX `fk_file_identity1_idx` (`owner_id` ASC),
  CONSTRAINT `fk_file_file1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `file` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_identity1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `identity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `album_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `album_item` ;

CREATE TABLE IF NOT EXISTS `album_item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` TEXT NOT NULL,
  `type` TEXT NOT NULL COMMENT 'EMBED_URL' /* comment truncated */ /*AUDIO_URL
VIDEO_URL
IMAGE_URL
FILE*/,
  `description` TEXT NULL,
  `url` TEXT NULL,
  `file_id` INT UNSIGNED NULL,
  `thumbnail_file_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_media_item_file1_idx` (`file_id` ASC),
  INDEX `fk_album_item_file1_idx` (`thumbnail_file_id` ASC),
  CONSTRAINT `fk_media_item_file1`
    FOREIGN KEY (`file_id`)
    REFERENCES `file` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album_item_file1`
    FOREIGN KEY (`thumbnail_file_id`)
    REFERENCES `file` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `album` ;

CREATE TABLE IF NOT EXISTS `album` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` TEXT NOT NULL,
  `owner_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_album_identity1_idx` (`owner_id` ASC),
  CONSTRAINT `fk_album_identity1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `identity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `album_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `album_items` ;

CREATE TABLE IF NOT EXISTS `album_items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `album_id` INT UNSIGNED NOT NULL,
  `album_item_id` INT UNSIGNED NOT NULL,
  `index` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_album_items_album1_idx` (`album_id` ASC),
  INDEX `fk_album_items_album_item1_idx` (`album_item_id` ASC),
  CONSTRAINT `fk_album_items_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album_items_album_item1`
    FOREIGN KEY (`album_item_id`)
    REFERENCES `album_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock_transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_transaction` ;

CREATE TABLE IF NOT EXISTS `stock_transaction` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `identity_id` INT UNSIGNED NOT NULL,
  `create_time` DATETIME NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stock_item_identity1_idx` (`identity_id` ASC),
  CONSTRAINT `fk_stock_item_identity1`
    FOREIGN KEY (`identity_id`)
    REFERENCES `identity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `authentication_service`
-- -----------------------------------------------------
START TRANSACTION;
USE `myapp`;
INSERT INTO `authentication_service` (`id`, `name`, `system_adapter_service`, `enabled`) VALUES (1, 'Facebook', 'facebook', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `identity`
-- -----------------------------------------------------
START TRANSACTION;
USE `myapp`;
INSERT INTO `identity` (`id`, `enabled`, `authentication_enabled`, `registered_time`, `display_name`) VALUES (1, 1, 1, '2014-01-01 12:00:00', 'admin');
INSERT INTO `identity` (`id`, `enabled`, `authentication_enabled`, `registered_time`, `display_name`) VALUES (2, 1, 1, '2014-01-01 12:00:00', 'Matus');
INSERT INTO `identity` (`id`, `enabled`, `authentication_enabled`, `registered_time`, `display_name`) VALUES (3, 1, 1, '2014-01-01 12:00:00', 'Tomas');

COMMIT;


-- -----------------------------------------------------
-- Data for table `oauth_clients`
-- -----------------------------------------------------
START TRANSACTION;
USE `myapp`;
INSERT INTO `oauth_clients` (`client_id`, `client_secret`, `redirect_uri`, `grant_types`, `scope`, `user_id`) VALUES ('testuser', '$2y$10$jCy1IEQh9yALO/kbYODkyOAY4gCvapA/BT7nrOQUUoqnfMfsz1nFC', 'http://myapp.local/', NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `oauth_users`
-- -----------------------------------------------------
START TRANSACTION;
USE `myapp`;
INSERT INTO `oauth_users` (`username`, `password`, `first_name`, `last_name`) VALUES ('testuser', '$2y$10$jCy1IEQh9yALO/kbYODkyOAY4gCvapA/BT7nrOQUUoqnfMfsz1nFC', 'test', 'user');

COMMIT;


-- -----------------------------------------------------
-- Data for table `file`
-- -----------------------------------------------------
START TRANSACTION;
USE `myapp`;
INSERT INTO `file` (`id`, `owner_id`, `parent_id`, `filesystem`, `filesystem_path`, `filesystem_error`, `type`, `name`, `mime_type`, `create_time`, `size`) VALUES (1, 1, NULL, 'public', '', NULL, 'DIR', 'Public', NULL, '2014-01-01 00:00:00', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `album_item`
-- -----------------------------------------------------
START TRANSACTION;
USE `myapp`;
INSERT INTO `album_item` (`id`, `title`, `type`, `description`, `url`, `file_id`, `thumbnail_file_id`) VALUES (1, 'Helena Jesele \'Sun Is Rising\' Official Video', 'EMBED_URL', 'Helena Jesele \'Sun Is Rising\' Official Video', '//www.youtube.com/embed/8c9qDb3gaiI', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `album`
-- -----------------------------------------------------
START TRANSACTION;
USE `myapp`;
INSERT INTO `album` (`id`, `title`, `owner_id`) VALUES (1, 'Featured', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `album_items`
-- -----------------------------------------------------
START TRANSACTION;
USE `myapp`;
INSERT INTO `album_items` (`id`, `album_id`, `album_item_id`, `index`) VALUES (1, 1, 1, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `stock_transaction`
-- -----------------------------------------------------
START TRANSACTION;
USE `myapp`;
INSERT INTO `stock_transaction` (`id`, `identity_id`, `create_time`, `amount`) VALUES (1, 2, '2014-07-31 12:00:00', 6);
INSERT INTO `stock_transaction` (`id`, `identity_id`, `create_time`, `amount`) VALUES (2, 2, '2014-07-31 18:00:00', -1);
INSERT INTO `stock_transaction` (`id`, `identity_id`, `create_time`, `amount`) VALUES (3, 3, '2014-07-31 18:15:00', -1);

COMMIT;

