-- MySQL Script generated by MySQL Workbench
-- Tue 13 May 2014 01:05:53 BST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myapp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `myapp` ;

-- -----------------------------------------------------
-- Table `authentication_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authentication_service` ;

CREATE TABLE IF NOT EXISTS `authentication_service` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `system_adapter_service` TEXT NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `identity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `identity` ;

CREATE TABLE IF NOT EXISTS `identity` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `enabled` TINYINT(1) NOT NULL,
  `authentication_enabled` TINYINT(1) NOT NULL,
  `registered_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `identity_authentication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `identity_authentication` ;

CREATE TABLE IF NOT EXISTS `identity_authentication` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_id` INT UNSIGNED NOT NULL,
  `service_id` INT UNSIGNED NOT NULL,
  `identity` TEXT NOT NULL,
  `user_profile` TEXT NULL COMMENT 'json serialized',
  PRIMARY KEY (`id`),
  INDEX `fk_identity_authentication_authentication_service_idx` (`service_id` ASC),
  INDEX `fk_identity_authentication_identity1_idx` (`owner_id` ASC),
  CONSTRAINT `fk_identity_authentication_authentication_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `authentication_service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_identity_authentication_identity1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `identity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Used to store authentication values e.g. facebook userid etc.';


-- -----------------------------------------------------
-- Table `identity_oauth_client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `identity_oauth_client` ;

CREATE TABLE IF NOT EXISTS `identity_oauth_client` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_id` INT UNSIGNED NOT NULL,
  `authentication_service_id` INT UNSIGNED NOT NULL,
  `access_token` TEXT NOT NULL,
  `expires` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_identity_oauth_client_authentication_service1_idx` (`authentication_service_id` ASC),
  INDEX `fk_identity_oauth_client_identity1_idx` (`owner_id` ASC),
  CONSTRAINT `fk_identity_oauth_client_authentication_service1`
    FOREIGN KEY (`authentication_service_id`)
    REFERENCES `authentication_service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_identity_oauth_client_identity1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `identity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `authentication_service`
-- -----------------------------------------------------
START TRANSACTION;
USE `myapp`;
INSERT INTO `authentication_service` (`id`, `name`, `system_adapter_service`, `enabled`) VALUES (1, 'Facebook', 'facebook', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `identity`
-- -----------------------------------------------------
START TRANSACTION;
USE `myapp`;
INSERT INTO `identity` (`id`, `enabled`, `authentication_enabled`, `registered_time`) VALUES (1, 1, 1, '2014-01-01 12:00:00');

COMMIT;

