<?php
/**
 * @var \KapSecurity\Authentication\Result $result
 */
$result = $this->result;
$res = [
    'code' => $result->getCode(),
    'identityId' => $result->getIdentityId(),
    'messages' => $result->getMessages(),
    'userProfile' => $result->getUserProfile() ? $result->getUserProfile()->getArrayCopy() : null
];


$this->layout()->setTemplate('layout/dialog');
?>
<script>
    require(['angular', 'module/KapLogin'], function(angular, kapLoginModule) {
        kapLoginModule.constant('loginCallbackResult', <?=json_encode($res)?>);
        angular.bootstrap(document, ['KapLogin']);
    });
</script>
<div ng-controller="loginCallbackController">
    {{status}}
</div>