<?php
$this->ng('ng-app', 'MyApp');
?>
<div id="ng-app" ng-controller="demoController" class="container ng-cloak">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">MyApp v0.1</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                </ul>
            </div>
        </div>
    </div>
    
    <h1>Well done!</h1>
    <p>
        If you see contributors table with some records below, you are good to start some real coding now!
    </p>
    <h2>Contributors</h2>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th colspan="4">
                    <span ng-show="loading">Loading ...</span>
                    <span ng-show="!loading">Total: {{totalItems}}, Page item count: {{pageSize}}</span>
                </th>
            </tr>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Note</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="item in items">
                <td>{{item.id}}</td>
                <td>{{item.name}}</td>
                <td>{{item.email}}</td>
                <td>{{item.note}}</td>
            </tr>
        </tbody>
    </table>
    <pagination items-per-page="pageSize" total-items="totalItems" ng-model="currentPage" ng-change="pageChanged()"></pagination>
</div>