<?php
$this->requireJs('module/MyApp');
?>
<div ng-controller="demoController" class="container ng-cloak">
    <h1>Well done!</h1>
    <p>
        If you see contributors table below with some records below, all is good and you are good to start doing some real coding now!
    </p>
    <h2>Contributors</h2>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th colspan="4">
                    <span ng-show="loading">Loading ...</span>
                    <span ng-show="!loading">Total: {{totalItems}}, Page item count: {{pageSize}}</span>
                </th>
            </tr>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Note</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="item in items">
                <td>{{item.id}}</td>
                <td>{{item.name}}</td>
                <td>{{item.email}}</td>
                <td>{{item.note}}</td>
            </tr>
        </tbody>
    </table>
    <pagination items-per-page="pageSize" total-items="totalItems" ng-model="currentPage" ng-change="pageChanged()"></pagination>
</div>